### ISSUE TITLE
Other probabilities are not updated after a single probability is modified

### ISSUE THREAD

**Issue by markheckmann** [markheckmann/gridsampler#38] opened 2016-11-18 17:59 UTC
When the value for a single probability is changed, the other values should be updated accordingly. Also, it should not be possible to assign a value higher than 1 for any probability. 
In the figure, a value of 10 was possible.

![image](https://cloud.githubusercontent.com/assets/152927/20440548/e6c54c7e-adc0-11e6-84ee-f4c010ccc5ca.png)

**Comment by jemus42** [comment] 2016-11-19 19:05
I fixed the second part by auto-updating the probabilities if they're above 1 now, but I'm not sure how to properly fix the first part. I remember attempting to fix this a while ago, but after a few fruitless attempts I figured that the functions using these probability vectors are scaling them back to sum up to 1 anyway.

**Comment by markheckmann** [comment] 2016-11-19 19:07
Yes, it is not a problem for the calculation, but simply wrong to display probabilities that do not sum up to one. In the old GTK+ GUI there was a function rescaling the prob vector to one after every change. Can't we do the same here?

**Comment by jemus42** [comment] 2016-11-19 19:14
I just pushed a fix to try that, but it appears that simply overwriting the probabilities with `probs/sum(probs)` is not enough.

**Comment by markheckmann** [comment] 2016-11-19 19:17
Okay, please try to fix that somehow. I will finish the revised manuscript tomorrow. If by Monday we do not have a solution, I will help looking into it.

**Comment by jemus42** [comment] 2016-11-19 22:02
It should work as intended now. At least I hope so, because if not, I ran out of ideas.

**Closed as completed** 2016-11-19 22:01 UTC
